version: '3.8'

services:
  app:
    build: .
    container_name: emareidi
    ports:
      - "8400:8400"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
